-- DDL

CREATE TABLE IF NOT EXISTS USERS
(
    ID        SERIAL,
    EMAIL     VARCHAR(50) UNIQUE,
    PASSWORD  VARCHAR(128),
    FIRSTNAME VARCHAR(50),
    LASTNAME  VARCHAR(50),
    ROLE      VARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRODUCTS
(
    ID    SERIAL,
    NAME  VARCHAR(50),
    PRICE INTEGER,
    IMAGE VARCHAR(128),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ADDRESSES
(
    ID       SERIAL,
    USER_ID  INTEGER,
    COUNTRY  VARCHAR(40),
    ADDRESS  VARCHAR(50),
    CITY     VARCHAR(40),
    POSTCODE VARCHAR(10),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ORDERS
(
    ID         SERIAL,
    USER_ID    INTEGER,
    PRODUCT_ID INTEGER,
    ADDRESS_ID INTEGER,
    AMOUNT     INTEGER,
    SEND       BOOLEAN,
    PRIMARY KEY (ID),
    CONSTRAINT fk_user
        FOREIGN KEY (USER_ID)
            REFERENCES USERS (ID) MATCH SIMPLE
            ON DELETE CASCADE,
    CONSTRAINT fk_product
        FOREIGN KEY (PRODUCT_ID)
            REFERENCES PRODUCTS (ID) MATCH SIMPLE
            ON DELETE CASCADE,
    CONSTRAINT fk_address
        FOREIGN KEY (ADDRESS_ID)
            REFERENCES ADDRESSES (ID) MATCH SIMPLE
            ON DELETE CASCADE
);

COMMIT;