-- DDL

CREATE TABLE IF NOT EXISTS USERS
(
    ID        BIGSERIAL,
    EMAIL     VARCHAR(50) UNIQUE,
    PASSWORD  VARCHAR(128),
    FIRSTNAME VARCHAR(50),
    LASTNAME  VARCHAR(50),
    ROLE      VARCHAR(50),
    ACTIVE    BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRODUCTS
(
    ID     BIGSERIAL,
    NAME   VARCHAR(50) UNIQUE,
    PRICE  INTEGER,
    IMAGE  VARCHAR(128),
    ACTIVE BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ORDERS
(
    ID       BIGSERIAL,
    USER_ID  BIGINT,
    COUNTRY  VARCHAR(40),
    ADDRESS  VARCHAR(50),
    CITY     VARCHAR(40),
    POSTCODE VARCHAR(10),
    SEND     BOOLEAN NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT user_fk FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS_ORDERS
(
    ID         BIGSERIAL,
    ORDER_ID   BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    AMOUNT     INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT order_fk FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS (ID) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT product_fk FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS (ID) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

COMMIT;