-- DDL

CREATE TABLE public.ADDRESS
(
    ID       SERIAL,
    ADDRESS  VARCHAR(50),
    CITY     VARCHAR(40),
    POSTCODE VARCHAR(10),
    PRIMARY KEY (ID)
);

CREATE TABLE public.USER
(
    ID        SERIAL,
    EMAIL     VARCHAR(50) UNIQUE,
    PASSWORD  VARCHAR(128),
    FIRSTNAME VARCHAR(50),
    LASTNAME  VARCHAR(50),
    ROLE      VARCHAR(50),
    ADDRESS   INTEGER,
    PRIMARY KEY (ID),
    CONSTRAINT fk_address
        FOREIGN KEY (ADDRESS)
            REFERENCES public.ADDRESS (ID) MATCH SIMPLE
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

CREATE TABLE public.PRODUCT
(
    ID    SERIAL,
    NAME  VARCHAR(50),
    PRICE INTEGER,
    IMAGE VARCHAR(128),
    PRIMARY KEY (ID)
);

CREATE TABLE public.ORDER
(
    ID         SERIAL,
    USER_ID    INTEGER,
    PRODUCT_ID INTEGER,
    AMOUNT     INTEGER,
    SEND       BOOLEAN,
    PRIMARY KEY (ID),
    CONSTRAINT fk_user
        FOREIGN KEY (USER_ID)
            REFERENCES public.USER (ID) MATCH SIMPLE
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    CONSTRAINT fk_item
        FOREIGN KEY (PRODUCT_ID)
            REFERENCES public.PRODUCT (ID) MATCH SIMPLE
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

COMMIT;